# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"

# Maintain dependencies for npm
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
   
# Maintain dependencies for pip
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "daily"
