# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/freedata_gui"
    schedule:
      interval: "monthly"
    target-branch: "develop"

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"