#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 23 11:13:57 2020

@author: DJ2LS
"""


# FreeDV Defaults

FREEDV_DATA_MODE = 12
FREEDV_SIGNALLING_MODE = 7

FREEDV_DATA_BYTES_PER_FRAME = 0
FREEDV_DATA_PAYLOAD_PER_FRAME = 0
FREEDV_SIGNALLING_BYTES_PER_FRAME = 0
FREEDV_SIGNALLING_PAYLOAD_PER_FRAME = 0

# Server Defaults
HOST = "localhost"
PORT = 3000


#AUdio Defaults
AUDIO_INPUT_DEVICE = 1
AUDIO_OUTPUT_DEVICE = 1
TX_SAMPLE_STATE = None
RX_SAMPLE_STATE = None

AUDIO_SAMPLE_RATE_RX = 44100
AUDIO_SAMPLE_RATE_TX = 44100
MODEM_SAMPLE_RATE = 8000 #8000
AUDIO_FRAMES_PER_BUFFER = 2048
AUDIO_CHANNELS = 1


#TNC DEFAULTS
# ARQ
TX_N_MAX_RETRIES = 3
TX_N_RETRIES = 0



ARQ_TX_N_FRAMES_PER_BURST = 0
ARQ_TX_N_BURSTS = 0

ARQ_PAYLOAD_PER_FRAME = 0
ARQ_ACK_WAITING_FOR_ID = 0
ARQ_RX_BURST_BUFFER = []
ARQ_RX_FRAME_BUFFER = []
ARQ_RX_FRAME_N_BURSTS = 0
ARQ_ACK_PAYLOAD_PER_FRAME = 0
ARQ_ACK_RECEIVED = 0
ARQ_ACK_TIMEOUT = 0
ARQ_ACK_TIMEOUT_SECONDS = 10.0

FRAME_CRC = b''
FRAME_BOF = b'\xAA\xAA'
FRAME_EOF = b'\xFF\xFF'

ARQ_N_SENT_FRAMES = 0


# ARQ STATES:
# IDLE
# RECEIVING_DATA
# SENDING_DATA
# RECEIVING_ACK
# SENDING_ACK
# ACK_RECEIVED
#
#
#
ARQ_STATE = 'RECEIVING_DATA'

# ------- TX BUFFER
TX_BUFFER_SIZE = 0
TX_BUFFER = []
# ------- RX BUFFER
RX_BUFFER = []
RX_BUFFER_SIZE = 0

