#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 23 11:13:57 2020

@author: parallels
"""

# Modem States
MODEM_RECEIVE = True


# FreeDV Defaults
FREEDV_MODE = 12
FREEDV_BYTES_PER_FRAME = 0
FREEDV_PAYLOAD_PER_FRAME = 0

# Server Defaults
HOST = "localhost"
PORT = 3000


#AUdio Defaults
DEFAULT_FRAMES = 1024
AUDIO_INPUT_DEVICE = 1
AUDIO_OUTPUT_DEVICE = 1
TX_SAMPLE_STATE = None
RX_SAMPLE_STATE = None
AUDIO_SAMPLE_RATE = 8000
MODEM_SAMPLE_RATE = 8000
AUDIO_FRAMES_PER_BUFFER = 1024
AUDIO_CHANNELS = 1


#TNC DEFAULTS
# ----ARQ STOP AND WAIT
TX_N_MAX_RETRIES = 3
TX_N_RETRIES = 3
ACK_RECEIVED = 0
ACK_TIMEOUT = 0
ACK_TIMEOUT_SECONDS = 15.0
ACK_RX_TIMEOUT = 0
ACK_RX_TIMEOUT_SECONDS = 15.0

ARQ_TX_N_FRAMES = 2
ARQ_PAYLOAD_PER_FRAME = 0
ARQ_ACK_WAITING_FOR_ID = 0

ARQ_RX_BURST_BUFFER = []
ARQ_RX_FRAME_BUFFER = []

FRAME_CRC = b''


# ------- TX BUFFER
TX_BUFFER_SIZE = 0


