name: Feature Request
description: Suggest an idea for FreeDATA
title: "[Feature Request]: "
labels: "enhancement :sparkles:"
body:

- type: textarea
  attributes:
    label: Problem Description
    description: Please add a clear and concise description of the problem you are seeking to solve with this feature request.
  validations:
    required: true
- type: textarea
  attributes:
    label: Proposed Solution
    description: Describe the solution you'd like in a clear and concise manner.
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternatives Considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: Add any other context about the problem here.
  validations:
    required: false
