name: build_gui
on: [push]

jobs:
  build_i686_x64_release:
    name: Build FreeDATA GUI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        include:
          - os: ubuntu-20.04
            electron_parameters: "-p always"

          - os: macos-latest
            electron_parameters: "-p always"

          - os: windows-latest
            electron_parameters: "-p always --x64 --ia32"

    steps:
      - name: Checkout code for ${{ matrix.platform.name }}
        uses: actions/checkout@v4
        with:
          repository: DJ2LS/FreeDATA
      - name: Electron Builder
        env: # Setting environment variables for the entire job
          GH_TOKEN: ${{ secrets.github_token }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
        working-directory: freedata-gui
        run: |
          npm i
          npm run release